work_schedule/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from shift import views
from shift.models import Post
from django.contrib.auth.models import Group

admin.site.site_title = '管理'
admin.site.site_header = 'システム管理サイト'
admin.site.index_title = 'メニュー'
admin.site.unregister(Group)

urlpatterns = [
    path('dahutos-admin/', admin.site.urls),
    path("", login_required(views.Index.as_view()), name="index"),
    path('', include("django.contrib.auth.urls")),
    path("sign-up/", views.SignUpView.as_view(), name="signup"),
    path('user_update/<slug:pk>', views.UserUpdate.as_view(), name="user_update"),
    path('month_with_forms/', views.MonthWithFormsCalendar.as_view(), name="month_with_forms"),
    path('month_with_forms/<int:year>/<int:month>/', views.MonthWithFormsCalendar.as_view(), name="month_with_forms"),
    path('index/', views.IndexPost.as_view(), name="index_post"),
    path('index/<int:year>/<int:month>/<int:day>/', views.IndexPost.as_view(), name="index_post"),
    path('comlite/', views.Complite.as_view(), name="complite"),
    path('update/<pk>', views.Update.as_view(), name="update"),
    path('delete/<pk>', views.Delete.as_view(), name="delete"),
    path('mypage/',views.Mypage.as_view(), name="mypage"),
    path('mypage/user_shift/<pk>',views.UserShift.as_view(), name="user_shift"),
    path('import/',views.ShiftImport.as_view(), name="import"),
    path('shift/',views.ShiftView.as_view(), name="shift"),
    path('shift/<int:year>/<int:month>/<int:day>/', views.ShiftView.as_view(), name="shift"),
    path('shift/update/<pk>', views.ShiftUpdate.as_view(), name="shift_update"),
    path('shift/delete/<pk>', views.ShiftDelete.as_view(), name="shift_delete"),
    path('shift/index/', views.ShiftIndex.as_view(), name='shift_index'),
]

shift/models.py
from django.db import models
from django.apps.config import AppConfig
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractUser,UserManager
import datetime
from django.utils import timezone
from django.urls import reverse_lazy

class UserManager(UserManager):
    pass

class User(AbstractUser):
    email = models.EmailField('メールアドレス', unique=False, blank=True)
    full_name = models.CharField('氏名', null=True, max_length=255,)
    class Meta:
        verbose_name = verbose_name_plural = _('アカウント')

    def get_absolute_url(self):
        return reverse_lazy("/")

    def __str__(self):
        return str(self.full_name)


class Post(models.Model):
    time_list=(('1','9:00'),('2','10:00'),('3','11:00'),('4','12:00'),('5','13:00'),
             ('6','14:00'),('7','15:00'),('8','16:00'),('9','17:00'),('10','18:00'),
             ('11','19:00'),('12','20:00'),('13','21:00'),('14','22:00'),('15','23:00'),
             ('16','24:00')
            )
    start_time = models.CharField('開始',
        blank=True,
        null=True,
        choices=time_list,
        max_length=255,)

    end_time = models.CharField('終了',
        blank=True,
        null=True,
        choices=time_list,
        max_length=255,)

    date = models.DateField('日付',)

    name = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='related_user',
        verbose_name="ユーザー",
        )

    published = models.BooleanField(
        default=True,
        verbose_name="編集",
        )

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = verbose_name_plural = _('希望シフト')

class Shift(models.Model):

    start_time = models.TimeField('開始時間',
        default=datetime.time(0, 0, 0))

    end_time = models.TimeField('終了時間',
        default=datetime.time(0, 0, 0))

    time = models.TimeField('休憩時間',
            default=datetime.time(0, 0))

    description = models.TextField('メモ',
        blank=True)

    date = models.DateField('日付',)

    name = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='related_shift',
        verbose_name="ユーザー",
        )

    def __str__(self):
        return str(self.date)

    class Meta:
        verbose_name = verbose_name_plural = _('完成シフト')

shift/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import User, Post, Shift
from django import forms
import datetime as dt

class SimpleScheduleForm(forms.ModelForm):
    """シンプルなスケジュール登録用フォーム"""
    class Meta:
        model = Post
        fields = ('start_time','end_time','date',)
        widgets = {
            'start_time': forms.Select,
            'end_time': forms.Select,
            'date': forms.HiddenInput,}

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","full_name","password1", "password2")

    def save(self, commit=True):
        # commit=Falseだと、DBに保存されない
        user = super().save(commit=False)
        user.save()
        return user

class SearchForm(forms.Form):
    startdate = forms.DateInput()
    enddate = forms.DateInput()

class CSVUploadForm(forms.Form):
    file = forms.FileField(label='CSVファイル')

class BS4ScheduleForm(forms.ModelForm):
    """Bootstrapに対応するためのModelForm"""

    class Meta:
        model = Shift
        fields = ('start_time', 'end_time','time','description')
        widgets = {
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            if end_time > dt.time(hour=5):
                raise forms.ValidationError(
                    '終了時間は、開始時間よりも後にしてください'
                    )
        return end_time

shift/views.py
# ListViewとDetailViewを取り込み
from django.views.generic import ListView, DetailView
import datetime
from django.shortcuts import redirect, render
from django.views import generic
from . import mixins
from .models import Post, User, Shift
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views import generic
from . import mixins
from .forms import SimpleScheduleForm, SignUpForm, SearchForm
from django.views.generic.edit import CreateView
from django.http import HttpResponse
from django.views.generic.edit import UpdateView
from django.utils.translation import ugettext_lazy as _
import csv
import io
import urllib
from .forms import CSVUploadForm, BS4ScheduleForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class Index(ListView):
    template_name="registration/index.html"
    model = Post
    paginate_by = 5

    def get_queryset(self):
        query_set = Post.objects.filter(
            name=self.request.user).order_by('-date')

        return query_set

class Mypage(ListView):
    template_name = 'admin/mypage.html'
    model = User

    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get('startdate', None),
            self.request.POST.get('enddate', None),
        ]
        request.session['form_value'] = form_value

        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        startdate = ''
        enddate = ''
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            startdate = form_value[0]
            enddate = form_value[1]
        default_data = {'startdate': startdate,
                        'enddate': enddate,
                        }
        test_form = SearchForm(initial=default_data) # 検索フォーム
        context['test_form'] = test_form
        context['date_range'] = ','.join([startdate,enddate])
        context['range']= '〜'.join([startdate,enddate])

        return context

    def get(self, request, **kwargs):
        if not request.user.is_superuser:
            return redirect('/dahutos-admin/')
        return super().get(request)

def paginate_queryset(request, queryset, count):

    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

class UserShift(DetailView):
    template_name="admin/user_shift.html"
    model = User

    def post(self, request, *args, **kwargs):
        form_value = [
            self.request.POST.get('startdate', None),
            self.request.POST.get('enddate', None),
        ]
        request.session['form_value'] = form_value

        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs,):
        context = super().get_context_data(**kwargs)
        startdate = ''
        enddate = ''
        pk = self.kwargs.get('pk')
        user = User.objects.get(pk=pk)
        shift_objects = Shift.objects.filter(name=user).order_by('-date')
        post_objects = Post.objects.filter(name=user).order_by('-date')
        if 'form_value' in self.request.session:
            form_value = self.request.session['form_value']
            startdate = form_value[0]
            enddate = form_value[1]
        default_data = {'startdate': startdate,
                        'enddate': enddate,
                        }
        test_form = SearchForm(initial=default_data) # 検索フォーム
        page_shift_obj = paginate_queryset(self.request, shift_objects, 5)
        page_post_obj = paginate_queryset(self.request, post_objects, 5)
        context['test_form'] = test_form
        context['date_range'] = ','.join([startdate,enddate])
        context['range']= '〜'.join([startdate,enddate])
        context['page_shift_obj'] = page_shift_obj
        context['page_post_obj'] = page_post_obj

        return context

    def get(self, request, **kwargs):
        if not request.user.is_superuser:
            return redirect('/dahutos-admin/')
        return super().get(request)

class Complite(ListView):
    template_name="shift/post_complite.html"
    model = Post

    def post(self, request):
        post = Post.objects.filter(name=request.user).update(published=False)
        print(request.user,'がシフトを完了しました。')

        return redirect('/')

class UserUpdate(UpdateView):
    template_name="registration/user_form.html"
    model = User
    fields = ["full_name","email"]
    success_url = "/"

    def get(self, request, **kwargs):
        if not User.objects.get(id=self.kwargs['pk'])==request.user:
            return HttpResponse('不正なアクセスです。')
        return super().get(request)

class IndexPost(mixins.MonthCalendarMixin, ListView):
    template_name="shift/index_post.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        month_calendar_context = self.get_month_calendar()
        context.update(month_calendar_context)
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        day = self.kwargs.get('day')
        if year:
            context['date'] = datetime.date(year=int(year), month=int(month), day=int(day))
        return context

    def get(self, request, **kwargs):
        if not request.user.is_authenticated:
            return redirect('/')
        return super().get(request)

class Update(UpdateView):
    model = Post
    fields = ["start_time", "end_time",]
    success_url = "/mypage/"

    def get(self, request, **kwargs):
        if not request.user.is_superuser:
            if not Post.objects.get(id=self.kwargs['pk']).name==request.user:
                return HttpResponse('不正なアクセスです。')
            if not Post.objects.get(id=self.kwargs['pk']).published:
                return HttpResponse('不正なアクセスです。')
        return super().get(request)

from django.views.generic.edit import DeleteView

class Delete(DeleteView):
    model = Post
    success_url = "/mypage/"

    def get(self, request, **kwargs):
        if not request.user.is_superuser:
            if not Post.objects.get(id=self.kwargs['pk']).name==request.user:
                return HttpResponse('不正なアクセスです。')
            if not Post.objects.get(id=self.kwargs['pk']).published:
                return HttpResponse('不正なアクセスです。')
        return super().get(request)

class MonthWithFormsCalendar(mixins.MonthWithFormsMixin, generic.View):
    """フォーム付きの月間カレンダーを表示するビュー"""
    template_name = 'shift/month_with_forms.html'
    model = Post
    date_field = 'date'
    form_class = SimpleScheduleForm

    def get(self, request, **kwargs):
        context = self.get_month_calendar()
        if not request.user.is_authenticated:
            return redirect('/')
        return render(request,self.template_name,context,)

    def post(self, request, **kwaegs):
        context = self.get_month_calendar()
        form_list = context['month_formset']
        forms = []
        for form in form_list:
            if form.is_valid():
                start_time = form.cleaned_data.get('start_time')
                end_time = form.cleaned_data.get('end_time')
                date = form.cleaned_data.get('date')
                if not (start_time and end_time) == None:
                    if Post.objects.filter(date=date, name=request.user).count() != 0:
                        context["helptext_day"] = '同じ日付の編集は編集画面で行なってください。'
                        return render(request,self.template_name,context)
                    elif int(start_time)>=int(end_time):
                        context["helptext_time"] = '指定時間が間違ってます。'
                        return render(request,self.template_name,context,)
                    else:
                        forms.append([start_time,end_time,date])
        if forms == []:
            context["helptext_input"] = '未入力の部分があります。'
            return render(request,self.template_name,context,)
        else:
            for formset in forms:
                start_time = formset[0]
                end_time = formset[1]
                date = formset[2]
                Post.objects.create(start_time=start_time,
                                end_time=end_time,date=date,name=request.user)
            print(request.user,'がシフトを提出しました。')
            return redirect('/')

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

class ShiftImport(generic.FormView):

    template_name = 'admin/import.html'
    success_url = '/dahutos-admin/'
    form_class = CSVUploadForm

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form_name'] = 'csvdownload'
        return ctx

    def form_valid(self, form):
        """postされたCSVファイルを読み込み、役職テーブルに登録します"""
        csvfile = io.TextIOWrapper(form.cleaned_data['file'])
        reader = csv.reader(csvfile)
        for i,row in enumerate(reader):
            if i == 0:
                continue
            else:
                if User.objects.filter(username=row[4]).exists():
                    start_time = row[2].split('〜')[0]
                    end_time = row[2].split('〜')[1]
                    end_time_min = int(end_time.split(':')[0])*60+int(end_time.split(':')[1])
                    start_time_min = int(start_time.split(':')[0])*60+int(start_time.split(':')[1])
                    time_min_old = end_time_min - start_time_min
                    time_min = int(time_min_old - float(row[1])*60)
                    time = datetime.time(hour=time_min//60,minute=time_min%60)
                    if int(end_time.split(':')[0]) >= 24:
                        end_time = (str(int(end_time.split(':')[0])-24)

templates/shift/base.html
<!doctype HTML>
{% load static %}
<html>
    <head>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon_shift.png' %}"/>
        <link rel="touch-icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="shortcut icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="icon" sizes="192x192" href="{% static 'icon_shift.png' %}"/>
        <link rel="shortcut icon" sizes="32x32" href="{% static 'icon_shift.png' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'mypage.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'month_maru.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'month_with_forms.css' %}" />
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes" />

        <title>シフト提出</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">マイページ</a>
    <button class="navbar-toggler" type="button"
      data-toggle="collapse"
      data-target="#navmenu1"
      aria-controls="navmenu1"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navmenu1">
       <div class="navbar-nav">
         <a class="nav-item nav-link" href="{% url 'index_post'  %}">希望シフト一覧</a>
         <a class="nav-item nav-link" href="{% url 'shift'  %}">完成シフト一覧</a>
         <a class="nav-item nav-link" href="{% url 'shift_index'  %}">完成シフト確認</a>
     <a class="nav-item nav-link" href="{% url 'logout' %}"><font color="red">ログアウト</font></a>
    </div>
  </div>
</nav>
<div class="container mt-4">
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
      </div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
              integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
              crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
              integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
              crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
              integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
              crossorigin="anonymous"></script>
      {% block extrajs %}{% endblock %}
    </body>
</html>

templates/shift/index_post.html
{% extends "shift/base.html" %}

{% block main %}
{% load tag_library %}
    <a href="{% url 'index_post' month_previous.year month_previous.month　month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'index_post' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
      {% for w in week_names %}
              {% if w == '土' %}
                  <td class="table-primary text-center">
              {% elif w == '日' %}
                  <td class="table-success text-center">
              {% else %}
              <th class="table-info text-center">
              {% endif %}
               {{ w }}</th>
          {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
          <tr class="text-center">
              {% for day in week %}
              {% if day|jpholiday %}
                       <td class='table-danger'>
              {% elif day.weekday == 6 %}
                       <td class='table-danger'>
              {% elif day.weekday == 5 %}
                       <td class='table-primary'>
              {% else %}
              <td>
              {% endif %}
            {% if day|day_my_post:user %}
            <div class="maru size_normal pink1">
              <div class="letter3">
            {% else %}
            <div>
              <div>
            {% endif %}
            {% if month_current.month != day.month %}
            <a href="{% url 'index_post' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
            {% else %}
            <a href="{% url 'index_post' day.year day.month day.day %}">{{ day.day }}</a>
            {% endif %}
          </div>
        </div>
                </td>
            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>
<hr>
 {% if date %}
<table border="1" class="table table-striped">
  <tr>
<th>{{ date|date:"Y/m/d" }}{{ date | date:"l"|w_name}}</th>
 {% endif %}
{% if date|day_my_post:user %}
  <tr>
  {% for post in date|day_my_post:user %}
    <td>　{{ post.get_start_time_display }}〜{{ post.get_end_time_display }}　
      {% if post.published == True %}
      <a class="btn  btn-primary btn-xs" href="{% url 'update' post.id %}">編集</a>
    <a class="btn  btn-danger btn-xs" href="{% url 'delete' post.id %}">削除</a>
    {% else %}
    {% endif %}
    </td>
  {% endfor %}
  </tr>
</table>
{% else %}
</table>
{% endif %}
{% endblock %}

templates/shift/month.html
{% load tag_library %}
{% if user.is_staff %}
<a href="/mypage/">管理者画面へ</a>
{% endif %}
<br>
    <a href="{% url 'shift' month_previous.year month_previous.month　month_previous.day %}">前月</a>
{{ month_current | date:"Y年m月" }}
<a href="{% url 'shift' month_next.year month_next.month month_next.day %}">次月</a>

<table class="table" style="table-layout: fixed;">
    <thead>
    <tr>
      {% for w in week_names %}
              {% if w == '土' %}
                  <td class="table-primary text-center">
              {% elif w == '日' %}
                  <td class="table-success text-center">
              {% else %}
              <th class="table-info text-center">
              {% endif %}
               {{ w }}</th>
          {% endfor %}
    </tr>
    </thead>
    <tbody>
    {% for week in month_days %}
        <tr>
          <tr class="text-center">
              {% for day in week %}
              {% if day|jpholiday %}
                       <td class='table-danger'>
              {% elif day.weekday == 6 %}
                       <td class='table-danger'>
              {% elif day.weekday == 5 %}
                       <td class='table-primary'>
              {% else %}
              <td>
              {% endif %}
         {% if user.is_staff %}
           {% if day|day_admin_shift %}
          <div class="maru size_normal pink1">
            <div class="letter3">
           {% else %}
          <div>
            <div>
           {% endif %}
           {% if month_current.month != day.month %}
             <a href="{% url 'shift' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
           {% else %}
            <a href="{% url 'shift' day.year day.month day.day %}">{{ day.day }}</a>
           {% endif %}
        </div>
      </div>
            </td>
        {% else %}
            {% if day|day_my_shift:user %}
            <div class="maru size_normal pink1">
              <div class="letter3">
            {% else %}
            <div>
              <div>
            {% endif %}
            {% if month_current.month != day.month %}
                 <a href="{% url 'shift' day.year day.month day.day %}">{{ day | date:"m/d" }}</a>
            {% else %}
                <a href="{% url 'shift' day.year day.month day.day %}">{{ day.day }}</a>
            {% endif %}
          </div>
        </div>
        </td>
          {% endif %}

            {% endfor %}
        </tr>
    {% endfor %}
    </tbody>
</table>

templates/shift/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% if page_obj.number > 3 %}
     <li class="page-item">
       <a class="page-link" href="?page=1" aria-label="First">1</a>
     </li>
     {% endif %}

     {% if page_obj.number > 4 %}
     <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
     {% endif %}

     {% for link_page in page_obj.paginator.page_range %}
     {% if link_page == page_obj.number %}
     <li class="page-item active">
       <a class="page-link" href="?page={{ link_page }}">
         {{ link_page }}
       </a>
     </li>
     {% elif link_page < page_obj.number|add:3 and link_page > page_obj.number|add:-3 %}
     <li class="page-item">
       <a class="page-link" href="?page={{ link_page }}">
         {{ link_page }}
       </a>
     </li>
     {% endif %}
     {% endfor %}

     {% if page_obj.number < page_obj.paginator.num_pages|add:-3 %}
     <li class="page-item"><span class="page-link" aria-hidden="true">...</span></li>
     {% endif %}

     {% if page_obj.number < page_obj.paginator.num_pages|add:-2 %}
     <li class="page-item">
       <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">{{ page_obj.paginator.num_pages}}</a>
     </li>
     {% endif%}
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/shift/post_complite.html
{% extends "shift/base.html" %}

{% block main %}
<h2>完了確認</h2>
<p>本当に完了してもよろしいですか？</p>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="完了" class="btn btn-danger" />
</form>
{% endblock %}

templates/shift/shift_form.html
{% extends 'shift/base.html' %}
{% block main %}
{% load tag_library %}
            {% include 'shift/month.html' %}
            <hr>
            <table border="1" class="table table-striped">
              <tr>
            <th>{{ object.date|date:"Y/m/d" }}{{ object.date | date:"l"|w_name}}
              </table>
            {% if object.end_time|date_comparison:object.date or user.is_staff %}
            <form action="" method="POST">
              {{ form.non_field_errors }}
              {% for field in form %}
              {{ field.label_tag }}
                          {{ field }}
                          {{ field.errors }}
              {% endfor %}
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block">変更</button>
            </form>
            {% else %}
            <table border="1" class="table table-striped">
            <tr>
              <th>開始〜終了</th>
              <th>勤務時間</th>
            </tr>
            <tr>
              <td>{{ object.start_time }}〜{{ object.end_time }}</td>
              <td>{{ object|work_time }}</td>
            </tr>
            </table>
              <form action="" method="POST">
                {% for field in form %}
                {% if forloop.counter == 4 %}
                {{ field.label_tag }}
                            {{ field }}
                {% endif %}
                {% endfor %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">変更</button>
              </form>
              {% endif %}
{% endblock %}


{% block extrajs %}
<link rel="stylesheet" type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
<script>
$(function () {
    // timedropper
    $("#id_start_time").timeDropper({
        format: "H:mm",
        setCurrentTime: false,
    });
    $("#id_end_time").timeDropper({
        format: "H:mm",
        setCurrentTime: false,
    });
    $("#id_time").timeDropper({
        format: "H:mm",
        setCurrentTime: false,
    });
});
</script>
{% endblock %}